# Generated by Django 3.1.3 on 2021-07-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='note',
            field=models.TextField(default=''),
        ),
    ]
