# Generated by Django 3.1.3 on 2022-05-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_graph_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='private',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='graph',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
