# Generated by Django 3.1.3 on 2022-05-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0005_auto_20220510_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
