# Generated by Django 3.1.3 on 2023-07-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0009_address_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='private',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
