# Generated by Django 3.1.3 on 2023-07-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0010_auto_20230712_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='private',
            field=models.CharField(default='', max_length=255),
        ),
    ]
