# Generated by Django 3.1.3 on 2023-07-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0011_auto_20230712_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='previews'),
        ),
    ]
