# Generated by Django 3.1.3 on 2023-09-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0013_remove_graph_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedGraphs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('graphId', models.IntegerField()),
            ],
        ),
    ]
